### PR TITLE
docker-compose for LEL1-2019 apps

### PR DESCRIPTION
**Pull request by geiralund**
TODOS:
[x ] Create token service
[ x] create "wait for" kafka up and running logic
[x] add dp-regel-api-arena-adapter
[ ] create "fake" inntekt in dp-inntekt-db (via flyway?)
[ x] Howto readme.. and scripts

### CODE REVIEW

**Review by gtcno — COMMENTED** [review]
Bra jobba!

Men hos meg så stopper bare compose up etter at ldap og kafka er blitt kjørt opp?

**Comment by geiralund** [comment]
mm, snodig. prøver du `docker-compose -f docker-compose-lel.yml up --remove-orphans --force-recreate --build` ?

**Comment by geiralund** [comment]
tar create "fake" inntekt in dp-inntekt-db (via flyway?) i en annen branch.

**Review by gtcno — APPROVED** [review]
gj

**Pull request merged**
